services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: airlinemanager-sqlserver
    environment:
      - ACCEPT_EULA=Y - SA_PASSWORD=YourStrong@Passw0rd - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - airlinemanager-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C
        -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  webapp:
    build:
      context: .
      dockerfile: AirlineManager/Dockerfile
    container_name: airlinemanager-webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AirlineManager;User
          Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - 5000:8080
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - airlinemanager-network
    restart: on-failure
volumes:
  sqlserver_data:
    driver: local
networks:
  airlinemanager-network: null
  driver: bridge
